### ISSUE TITLE
依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by yukasansan** [yukasansan/chat-space#18]
# IPアドレス
54.199.91.161

**Comment by mo1015** [comment]
信濃さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○アイコンの位置が見本と異なる
○サイドバーの「グループ名」、「最新メッセージ」に下線が入っている
○contents上部の、 メンバー名の表示間隔が空いておらず、区切りが分からない
○投稿メッセージのユーザー名、日付の見た目が見本と異なる
　（投稿全体の位置も修正しましょう）**
<img width="1439" alt="修正" src="https://user-images.githubusercontent.com/62644781/83226953-08b29180-a1be-11ea-86b8-a11121e63b50.png">

**○「削除」「追加」ボタンの位置が見本通りでない（新規チャットグループ、チャットグループ編集ページ）**
<img width="1018" alt="修正2" src="https://user-images.githubusercontent.com/62644781/83227110-5af3b280-a1be-11ea-92bd-cfacd4e0d629.png">
↓見本
<img width="1439" alt="スクリーンショット 2020-05-29 15 09 00" src="https://user-images.githubusercontent.com/62644781/83227127-621ac080-a1be-11ea-9b1f-9622b0de2d45.png">


**○投稿フォームの実装が見本通りでない**
<img width="1439" alt="スクリーンショット 2020-05-29 15 02 43" src="https://user-images.githubusercontent.com/62644781/83226972-10723600-a1be-11ea-9a24-24c43e9d494f.png">
↓参考カリキュラム
<img width="691" alt="投稿フォーム見本" src="https://user-images.githubusercontent.com/62644781/83227220-9db58a80-a1be-11ea-98cd-9685b8a8e819.png">

修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

※今後実装に関する質問がありましたら、メンターに確認をお願いします！
